version: '3.8'

services:
  app:
    image: police-community-app
    build: .
    ports:
      - "6206:6206"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: police_community_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Console порт
    volumes:
      - ./docker/minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Если нужно добавить клиент для MinIO (опционально)
  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo 'Waiting for minio...' && sleep 1; done;
      /usr/bin/mc mb myminio/police-community-app;
      /usr/bin/mc policy set public myminio/police-community-app;
      tail -f /dev/null
      "